name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_CPP_wrapper:
    strategy:
      matrix:
        version: [Debug, Release]
        platform: [x64]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Compile LIB
      run: msbuild TTD.sln /target:TTD /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.version }}

  build_examples:
    strategy:
      matrix:
        version: [Debug, Release]
        platform: [x64]
        project: [example_api, example_calltree, example_diff, example_cov, example_tenet]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Compile ${{ matrix.project }}
      run: msbuild TTD.sln /target:${{ matrix.project }} /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.version }}
